services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: Carlos1009
      MYSQL_DATABASE: ecoswap
    ports:
      - "3307:3306"
    networks:
      - mynetwork
    volumes:
      - mysql_data:/var/lib/mysql

  spring-app:
    build: .
    container_name: my-spring-app
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ecoswap?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Carlos1009
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mysql_data:
