INSERT INTO user(address, cellphone_number, email, name, password, role) VALUES ('las gaviotas', 31221412, 'ruben@gmail.com', 'ruben castaño', '$2a$12$zLFql9djaJ3Uwx4zCqjRyugXstLaK6HbZpFu70aM/xPzFQFsQsfsK', 'ADMIN');
INSERT INTO user(address, cellphone_number, email, name, password, role) VALUES ('san jose', 4545, 'carlos@gmail.com', 'carlos de la rosa', '$2a$12$gg1BvSFnX307c1AJKJ26xeqcasUAqm9TY5FShw52jATJD35.3E68e', 'USER');
INSERT INTO user(address, cellphone_number, email, name, password, role) VALUES ('simom bolivar', 31221412, 'jesus@gmail.com', 'jesus santana', '$2a$13$SX/Y0ryLLUJWvQBOt6Agd.CmtDFLwk2nXy2NElxwZrcxmkyFbqlsa', 'USER');
INSERT INTO user(address, cellphone_number, email, name, password, role) VALUES ('el pozon', 4545, 'daniel@gmail.com', 'daniel', '$2a$13$JDAJvtPEM7cXoA3.LrZK6.sGdjoh8RKDzDXPKV9SVQmi0FL17P2qC', 'USER');


INSERT INTO product(category, condition_product ,description, product_status, title, user_id, release_date, image_product) VALUES ('Electrónica y Tecnología','nuevo' , 'pc gamer', 'activo', 'pc gamer', 1, '2024-05-05', 'http://localhost:8080/images/pc-gamer.jpeg' );
INSERT INTO product(category, condition_product ,description, product_status, title, user_id, release_date, image_product) VALUES ('Hogar y Muebles', 'usado' ,'nochero', 'activo', 'nochero', 2, '2024-05-05', 'http://localhost:8080/images/nochero.jpg');
INSERT INTO product(category, condition_product ,description, product_status, title, user_id, release_date, image_product) VALUES ('Electrónica y Tecnología','usado' , 'monitor', 'activo', 'monitor', 3, '2024-05-05', 'http://localhost:8080/images/monitor.jpg');
INSERT INTO product(category, condition_product ,description, product_status, title, user_id, release_date, image_product) VALUES ('Hogar y Muebles', 'usado' ,'mesa', 'activo', 'mesa', 4, '2024-05-05', 'http://localhost:8080/images/mesa-gamer.jpg');